### ISSUE TITLE
Can I run multiple containers at the same time?

### ISSUE THREAD

**Issue by droyuki** [oscar-martin/docker-zmq-sbt#1]
Hi, I'm trying to run a publish/subscribe pattern based on this image, but I got 
`java.lang.UnsatisfiedLinkError: Native Library /tmp/sbt_dddb9c3b/libjzmq.so already loaded in another classloader` when I create multiple container as subscriber, how can I solve this error?

**Comment by oscar-martin** [comment]
Hi, have you read this blog entry? http://omartin.me/articles/0mq-with-scala-using-docker.html
But anyway, this error happens to me when reusing the same container but not when creating multiple containers.

**Comment by droyuki** [comment]
yes, it did happens when reusing the same container.
I was misdirected haha
